export default () => ({
  port: parseInt(process.env.PORT, 10),
  nodeEnv: process.env.NODE_ENV,
  database: {
    host: process.env.DATABASE_HOST,
    port: parseInt(process.env.DATABASE_PORT, 10),
    name: process.env.DATABASE_NAME,
    user: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    ssl: process.env.DATABASE_SSL === 'true',
    poolMin: parseInt(process.env.DATABASE_POOL_MIN, 10),
    poolMax: parseInt(process.env.DATABASE_POOL_MAX, 10),
  },
  jwt: {
    secret: process.env.JWT_SECRET,
    expiresInSeconds: parseInt(process.env.JWT_EXPIRATION_SECONDS, 10),
    appAccessExpiresInSeconds: parseInt(process.env.JWT_APP_ACCESS_EXPIRATION_SECONDS || '', 10),
  },
  security: {
    deviceUuidSalt: process.env.DEVICE_UUID_SALT,
    otpSalt: process.env.OTP_SALT,
    maxPinAttempts: 5,
    temporaryLockoutMinutes: 15,
  },
  astpp: {
    host: process.env.ASTPP_HOST,
    port: parseInt(process.env.ASTPP_PORT, 10),
    database: process.env.ASTPP_DATABASE,
    user: process.env.ASTPP_USER,
    password: process.env.ASTPP_PASSWORD,
    tokenKeyHex: process.env.ASTPP_TOKEN_KEY_HEX,
    ivHex: process.env.ASTPP_IV_HEX,
    ssh: {
      host: process.env.ASTPP_SSH_HOST,
      port: parseInt(process.env.ASTPP_SSH_PORT, 10),
      username: process.env.ASTPP_SSH_USERNAME,
      privateKey: process.env.ASTPP_SSH_PRIVATE_KEY,
      privateKeyPath: process.env.ASTPP_SSH_PRIVATE_KEY_PATH,
    },
    imagesPath: process.env.ASTPP_IMAGES_PATH,
  },
  kafka: {
    brokers: process.env.KAFKA_BROKERS.split(','),
    clientId: process.env.KAFKA_CLIENT_ID,
    groupId: process.env.KAFKA_GROUP_ID,
    topics: {
      accounts: process.env.KAFKA_TOPIC_ACCOUNTS,
      applications: process.env.KAFKA_TOPIC_APPLICATIONS,
      applicantDetails: process.env.KAFKA_TOPIC_APPLICANT_DETAILS,
      dids: process.env.KAFKA_TOPIC_DIDS,
    },
  },
  sasapay: {
    enabled: process.env.SASAPAY_ENABLED === 'true',
    environment: process.env.SASAPAY_ENVIRONMENT,
    clientId: process.env.SASAPAY_CLIENT_ID,
    clientSecret: process.env.SASAPAY_CLIENT_SECRET,
    merchantCode: process.env.SASAPAY_MERCHANT_CODE,
    baseUrl: process.env.SASAPAY_BASE_URL,
    callbackUrl: process.env.SASAPAY_CALLBACK_URL,
    callbackSecurity: {
      allowedIps: process.env.SASAPAY_CALLBACK_ALLOWED_IPS.split(',').map((ip) => ip.trim()).filter(Boolean),
    },
  },
  notification: {
    url: process.env.NOTIFICATION_SERVICE_URL,
    apiKey: process.env.NOTIFICATION_SERVICE_API_KEY,
  },
});
