export default () => ({
  port: Number(process.env.PORT),
  nodeEnv: process.env.NODE_ENV,
  database: {
    host: process.env.DATABASE_HOST,
    port: Number(process.env.DATABASE_PORT),
    name: process.env.DATABASE_NAME,
    user: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    ssl: process.env.DATABASE_SSL === 'true',
    poolMin: Number(process.env.DATABASE_POOL_MIN),
    poolMax: Number(process.env.DATABASE_POOL_MAX),
    connectionTimeoutMillis: Number(process.env.DATABASE_CONNECTION_TIMEOUT_MS),
  },
  jwt: {
    secret: process.env.JWT_SECRET,
    expiresInSeconds: Number(process.env.JWT_EXPIRATION_SECONDS),
    appAccessExpiresInSeconds: Number(process.env.JWT_APP_ACCESS_EXPIRATION_SECONDS),
  },
  security: {
    deviceUuidSalt: process.env.DEVICE_UUID_SALT,
    otpSalt: process.env.OTP_SALT,
    maxPinAttempts: Number(process.env.MAX_PIN_ATTEMPTS),
    temporaryLockoutMinutes: Number(process.env.TEMPORARY_LOCKOUT_MINUTES),
  },
  astpp: {
    host: process.env.ASTPP_HOST,
    port: Number(process.env.ASTPP_PORT),
    database: process.env.ASTPP_DATABASE,
    user: process.env.ASTPP_USER,
    password: process.env.ASTPP_PASSWORD,
    baseUrl: process.env.ASTPP_BASE_URL,
    tokenKeyHex: process.env.ASTPP_TOKEN_KEY_HEX,
    ivHex: process.env.ASTPP_IV_HEX,
    tokenKey: process.env.ASTPP_TOKEN_KEY,
    ivDerived: process.env.ASTPP_IV_DERIVED,
    ivKey: process.env.ASTPP_IV_KEY,
    mysqlConnectionLimit: Number(process.env.ASTPP_MYSQL_CONNECTION_LIMIT),
    mysqlQueueLimit: Number(process.env.ASTPP_MYSQL_QUEUE_LIMIT),
    mysqlKeepAliveInitialDelay: Number(process.env.ASTPP_MYSQL_KEEP_ALIVE_INITIAL_DELAY_MS),
    mysqlKeepAlive: process.env.ASTPP_MYSQL_KEEP_ALIVE === 'true',
    mysqlWaitForConnections: process.env.ASTPP_MYSQL_WAIT_FOR_CONNECTIONS === 'true',
    ssh: {
      host: process.env.ASTPP_SSH_HOST,
      port: Number(process.env.ASTPP_SSH_PORT),
      username: process.env.ASTPP_SSH_USERNAME,
      privateKey: process.env.ASTPP_SSH_PRIVATE_KEY,
      privateKeyPath: process.env.ASTPP_SSH_PRIVATE_KEY_PATH,
    },
    imagesPath: process.env.ASTPP_IMAGES_PATH,
  },
  kafka: {
    brokers: process.env.KAFKA_BROKERS.split(',').map((broker) => broker.trim()),
    clientId: process.env.KAFKA_CLIENT_ID,
    groupId: process.env.KAFKA_GROUP_ID,
    notificationTopic: process.env.KAFKA_NOTIFICATION_TOPIC,
    topics: {
      accounts: process.env.KAFKA_TOPIC_ACCOUNTS,
      applications: process.env.KAFKA_TOPIC_APPLICATIONS,
      applicantDetails: process.env.KAFKA_TOPIC_APPLICANT_DETAILS,
      dids: process.env.KAFKA_TOPIC_DIDS,
    },
  },
  sasapay: {
    enabled: process.env.SASAPAY_ENABLED === 'true',
    kycEnabled: process.env.SASAPAY_KYC_ENABLED === 'true',
    environment: process.env.SASAPAY_ENVIRONMENT,
    clientId: process.env.SASAPAY_CLIENT_ID,
    clientSecret: process.env.SASAPAY_CLIENT_SECRET,
    merchantCode: process.env.SASAPAY_MERCHANT_CODE,
    baseUrl: process.env.SASAPAY_BASE_URL,
    callbackUrl: process.env.SASAPAY_CALLBACK_URL,
    callbackSecurity: {
      allowedIps: process.env.SASAPAY_CALLBACK_ALLOWED_IPS.split(',').map((ip) => ip.trim()).filter(Boolean),
    },
  },
  telemetry: {
    enabled: process.env.SENTRY_ENABLED === 'true',
  },
  publicUrl: process.env.PUBLIC_URL,
  apiKey: process.env.API_KEY,
  adminApiKey: process.env.ADMIN_API_KEY,
  cors: {
    allowedOrigins: process.env.CORS_ALLOWED_ORIGINS.split(',').map((origin) => origin.trim()).filter(Boolean),
    allowCredentials: process.env.CORS_ALLOW_CREDENTIALS === 'true',
  },
  rateLimit: {
    ttl: Number(process.env.RATE_LIMIT_TTL),
    limit: Number(process.env.RATE_LIMIT_LIMIT),
  },
});
